const char * htmlMessage =
"<!doctype html>\r\n"
"<head>\r\n"
"  <meta charset=\"utf-8\">\r\n"
"  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n"
"  <title>Light Switch with CSS3 &amp; HTML5</title>\r\n"
"  <meta name=\"description\" content=\"iOS Switch CSS3\">\r\n"
"  <meta name=\"author\" content=\"https://plus.google.com/116801469202683881648/\" />\r\n"
"  <meta property=\"og:title\" content=\"Light Switch with CSS3 &amp; HTML5\" />\r\n"
"  <meta property=\"og:description\" content=\"Demo website showcasing a skeumorphic realistic light switch.\" />\r\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=0.55\"/>\r\n"
"  <link rel='icon' href='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAS0lEQVR42s2SMQ4AIAjE+P+ncSYdasgNXMJgcyIIlVKPIKdvioAXyWBeJmVpqRZKWtj9QWAKZyWll50b8IcL9JUeQF50n28ckyb0ADG8RLwp05YBAAAAAElFTkSuQmCC' type='image/x-png' />"
"  <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\" />\r\n"
"</head>\r\n"
"\r\n"
"<body>\r\n"
"  <button>\r\n"
"    <span>\r\n"
"      <b>I</b> <b>O</b>\r\n"
"    </span>\r\n"
"  </button>\r\n"
"\r\n"
"  <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js\"></script>\r\n"
"  <script type=\"text/javascript\">\r\n"
"    /* iOS re-orientation fix */\r\n"
"    if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPad/i)) {\r\n"
"      var viewportmeta = document.querySelectorAll('meta[name=\"viewport\"]')[0];\r\n"
"      if (viewportmeta) {\r\n"
"        viewportmeta.content = 'width=device-width, minimum-scale=1.0, maximum-scale=1.0';\r\n"
"\r\n"
"        document.body.addEventListener('gesturestart', function() {\r\n"
"          viewportmeta.content = 'width=device-width, minimum-scale=0.25, maximum-scale=1.6';\r\n"
"        }, false);\r\n"
"      }\r\n"
"\r\n"
"      /* iOS hides Safari address bar */\r\n"
"      window.addEventListener(\"load\",function() {\r\n"
"        setTimeout(function() {\r\n"
"          window.scrollTo(0, 1);\r\n"
"        }, 1000);\r\n"
"      });\r\n"
"    }\r\n"
"\r\n"
"    $(document).ready(function(){\r\n"
"      /* on button click, toggle class \"OFF\" for the switch */\r\n"
"      $(\"button\").click(function () {\r\n"
"        $(\"button\").toggleClass(\"off\");\r\n"
"          if ($(\"button\").hasClass(\"\")) {\r\n"
"            //do nothing\r\n"
"        console.log(\"button on\");\r\n"
"        $.get(\"/on\");\r\n"
"          } else {\r\n"
"        console.log(\"button off\");\r\n"
"        $.get(\"/off\");\r\n"
"          }\r\n"
"      });\r\n"
"\r\n"
"      /* by default, darkness checkbox is checked (ON) but check anyhow */\r\n"
"      if ($('#enabled').is(':checked')) {\r\n"
"        darkness();\r\n"
"      }\r\n"
"\r\n"
"      /* on checkbox click, check if checked or not,\r\n"
"      call the function to initiate or remove the class of \"darkness\" if not */\r\n"
"      $('#enabled').click(function() {\r\n"
"        if ($('#enabled').is(':checked')) {\r\n"
"          darkness();\r\n"
"        } else {\r\n"
"          $(\".dark\").remove();\r\n"
"        }\r\n"
"      });\r\n"
"\r\n"
"      function darkness() {\r\n"
"        /* adds a div for the darkness when switch is OFF */\r\n"
"        $('html').append('<div class=\"dark\"></div>');\r\n"
"\r\n"
"        /* on button click, make darkness */\r\n"
"        $(\"button\").click(function () {\r\n"
"          /* avoid bug of inverting the switch i.e. \"1\" = OFF, \"0\" = ON;\r\n"
"          (by disabling the lights, clicking on the switch (OFF), re-enabling the lights and clicking the switch (ON) */\r\n"
"          if ($(\"button\").hasClass(\"\")) {\r\n"
"            //do nothing\r\n"
"          } else {\r\n"
"            $(\".dark\").fadeIn(800);\r\n"
"          }\r\n"
"        });\r\n"
"\r\n"
"        /* wherever on darkness is clicked, bring the light back and move the switch to ON */\r\n"
"        $(\".dark\").click(function () {\r\n"
"          $(\".dark\").fadeOut(2000);\r\n"
"          $(\"button\").removeClass();\r\n"
"        });\r\n"
"      }\r\n"
"    });\r\n"
"  </script>\r\n"
"</body>\r\n"
"</html>\r\n";
